language: ruby
rvm:
- 2.4.1
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake --trace db:create
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
- bundle exec rubocop --config .rubocop.yml
deploy:
  provider: heroku
  api_key:
    secure: rKc4f4tV8jJYjXH6DfZx
  app: https://rooks-on-rails.herokuapp.com
  on:
    repo: https://github.com/Rooks-on-Rails/rooks_on_rails
  run:
    - "rake db:migrate"
    - restart
